#!/bin/bash

set -euo pipefail

OS="$(uname -s | tr '[[:upper:]]' '[[:lower:]]')"

VERSION="0.10.2"
URL="https://github.com/bazelbuild/bazel-watcher/releases/download/v$VERSION/ibazel_${OS}_amd64"
CACHE_DIR="$HOME/.cache/ibazel-binary/$VERSION"
CACHE_FILE="$CACHE_DIR/bazel"
IDEA_DIR="$HOME/bin"
IDEA_FILE="$IDEA_DIR/ibazel"

function create_cache {
    mkdir -p $CACHE_DIR
    rm -f $CACHE_FILE
    wget -O $CACHE_FILE $URL
    chmod +x $CACHE_FILE
}

function create_link {
    mkdir -p $IDEA_DIR
    rm -f $IDEA_FILE
    ln -s $CACHE_FILE $IDEA_FILE
}

if [ ! -x $CACHE_FILE ]; then
    create_cache
fi

if [ ! -x $IDEA_FILE ]; then
    create_link
fi

if [[ "$(readlink -- "$IDEA_FILE")" != "$CACHE_FILE" ]]; then
    create_link
fi

export PATH="$(dirname ${BASH_SOURCE[0]}):$PATH"
$CACHE_FILE $@
